FROM node:13-alpine as builder
ADD package.json /tmp/package.json
ADD package-lock.json /tmp/package-lock.json
RUN cd /tmp && npm ci
RUN mkdir -p /app
RUN cp -a /tmp/node_modules /app/

WORKDIR /app

RUN npm run build

# The instructions for second stage
FROM node:13-alpine

WORKDIR /app

COPY --from=builder node_modules node_modules
COPY --from=builder dist dist

COPY . .

CMD [ "npm", "run", "start" ]